version: '3.8'
services:
  influxdb:
    image: influxdb:2.7.1
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
      - ./certs/influxdb-cert.pem:/etc/ssl/influxdb-cert.pem
      - ./certs/influxdb-key.pem:/etc/ssl/influxdb-key.pem
    command: >
      influxd --tls-cert /etc/ssl/influxdb-cert.pem --tls-key /etc/ssl/influxdb-key.pem
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    build: .
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: "https://influxdb:8086"
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    volumes:
      - ./dataset:/app/dataset
    command: ["python", "/app/insert_data.py"]

volumes:
  influxdb-data:
  influxdb-config:

